import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus } from 'lucide-react';
// ORTEX FAQ style

const faqs = [
  { q: 'How does the AI trading bot work?', a: 'Our AI analyzes price action, volume, sentiment, and on-chain data across 500+ signals per second. It automatically enters and exits long, short, and leveraged positions across crypto, stocks, and meme coins — 24/7.' },
  { q: 'What is the welcome bonus and how do I get it?', a: 'Every new user receives a $500 welcome bonus credited on first registration. No deposit required. The bonus is available immediately and can be used for trading or staking.' },
  { q: 'How does the referral system work?', a: 'Share your unique referral link. Every time someone signs up through your link and starts trading, you earn a $300 referral bonus automatically credited to your wallet.' },
  { q: 'What is the 1-week free trial?', a: 'New users get 7 days of completely fee-free access. The standard 5% AI trading fee is waived during this period. After the trial, the fee applies only to profits generated by the AI bot — never on deposits.' },
  { q: 'How does the weekly reward pool work?', a: 'Every week, $10,000 USDT is distributed to the top 3 highest stakers. Rankings update in real-time on the leaderboard. The pool resets every Monday at 00:00 UTC.' },
  { q: 'What is the 15% daily staking rate?', a: 'Our staking vault generates 15% interest on your balance every 24 hours, compounding automatically. This is powered by our AI arbitrage engine running across 40+ exchanges simultaneously — one of the highest verified daily yields in the market.' },
  { q: 'Can I withdraw my funds at any time?', a: 'Yes. There are no locked contracts or withdrawal restrictions. Withdrawals are processed within 24 hours. Our processing window is 8AM–8PM on weekdays. Your funds are always under your full control.' },
  { q: 'What leverage options are available?', a: 'We offer 1x, 2x, 5x, 10x, 25x, 50x, and 100x leverage on select assets. The AI manages risk with automatic stop-losses. Higher leverage is available on Pro accounts.' },
  { q: 'What assets can I trade?', a: 'Major cryptocurrencies (BTC, ETH, SOL, BNB), meme coins (DOGE, SHIB, PEPE), and major stocks (TSLA, AAPL, NVDA, AMZN, MSFT). New assets are added regularly.' },
  { q: 'How to Invest', a: 'Getting started is simple. Make your first cryptocurrency deposit from your account dashboard to activate your investment account. Once funded, your assets can participate in staking and AI-powered trading strategies designed to maximize opportunities within the platform.\n\nMonitor your investment performance, rewards, and account activity anytime through your personalized dashboard, with earnings and updates displayed automatically.' },
];

export default function FAQSection() {
  const [open, setOpen] = useState(null);
  return (
    <section id="faq" className="py-24 bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16">
          <p className="text-primary font-semibold text-sm uppercase tracking-widest mb-3">FAQ</p>
          <h2 className="font-display text-4xl sm:text-5xl font-bold text-gray-900">Common questions</h2>
        </motion.div>
        <div className="space-y-2">
          {faqs.map((faq, i) => (
            <motion.div key={i} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} transition={{ delay: i * 0.03 }}
              className="border border-gray-200 rounded-xl overflow-hidden">
              <button onClick={() => setOpen(open === i ? null : i)}
                className="w-full flex items-center justify-between p-5 text-left hover:bg-gray-50 transition-colors">
                <span className="font-semibold text-sm text-gray-900 pr-4">{faq.q}</span>
                {open === i ? <Minus className="w-4 h-4 text-primary flex-shrink-0" /> : <Plus className="w-4 h-4 text-gray-400 flex-shrink-0" />}
              </button>
              <AnimatePresence>
                {open === i && (
                  <motion.div initial={{ height: 0 }} animate={{ height: 'auto' }} exit={{ height: 0 }} className="overflow-hidden">
                    <p className="text-sm text-gray-500 px-5 pb-5 leading-relaxed">{faq.a}</p>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}