import React from 'react';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Button } from '@/components/ui/button';

// ORTEX "Ideas" section style - giant teal display word, lightbulb icon, tablet mockup
export default function StakingSection() {
  return (
    <section id="staking" className="bg-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20">

        {/* ORTEX Ideas-style: giant word, icon, tablet */}
        <div className="grid lg:grid-cols-2 gap-16 items-center mb-20">
          <motion.div initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}}>
            <h2 className="font-display font-bold leading-none mb-4" style={{fontSize:'clamp(4rem,10vw,8rem)',color:'hsl(174,65%,38%)'}}>
              Ideas
            </h2>
            {/* Lightbulb icon - ORTEX style */}
            <div className="mb-6">
              <svg width="64" height="64" viewBox="0 0 64 64" fill="none">
                <circle cx="32" cy="26" r="18" stroke="hsl(174,65%,38%)" strokeWidth="2.5" fill="none"/>
                <path d="M24 44 C24 44 28 48 32 48 C36 48 40 44 40 44" stroke="hsl(174,65%,38%)" strokeWidth="2.5" fill="none" strokeLinecap="round"/>
                <path d="M26 48 L38 48" stroke="hsl(174,65%,38%)" strokeWidth="2.5" strokeLinecap="round"/>
                <path d="M28 52 L36 52" stroke="hsl(174,65%,38%)" strokeWidth="2.5" strokeLinecap="round"/>
                <path d="M32 14 L32 10 M22 17 L19 14 M42 17 L45 14 M18 26 L14 26 M46 26 L50 26" stroke="hsl(174,65%,38%)" strokeWidth="2" strokeLinecap="round"/>
              </svg>
            </div>
            <p className="text-gray-700 font-display text-lg mb-6">
              Discover high-probability trading ideas generated by AI analysis — across crypto, stocks and meme coins.
            </p>
            <ul className="space-y-2 mb-8">
              {['AI-generated trade setups updated in real-time','Filter by asset type, leverage, risk score','Track performance of every idea over time','Get alerts when your saved ideas trigger'].map((f,i)=>(
                <li key={i} className="flex items-start gap-3">
                  <span className="w-1.5 h-1.5 rounded-full mt-2 flex-shrink-0" style={{background:'hsl(174,65%,38%)'}}/>
                  <span className="text-gray-600 font-display">{f}</span>
                </li>
              ))}
            </ul>
            <Link to="/register">
              <Button className="bg-red-500 hover:bg-red-600 text-white font-display font-semibold px-8 h-11 rounded-full">
                Explore Ideas
              </Button>
            </Link>
          </motion.div>

          {/* Tablet mockup - ORTEX style */}
          <motion.div initial={{opacity:0,x:30}} whileInView={{opacity:1,x:0}} viewport={{once:true}}>
            <div className="relative" style={{transform:'perspective(900px) rotateY(-5deg)'}}>
              <div className="bg-[#0d1117] rounded-2xl border-4 border-gray-800 shadow-2xl overflow-hidden">
                <div className="bg-[#161b22] px-4 py-2 flex items-center gap-2">
                  <div className="w-2 h-2 rounded-full bg-red-500/70"/><div className="w-2 h-2 rounded-full bg-yellow-500/70"/><div className="w-2 h-2 rounded-full bg-green-500/70"/>
                  <span className="text-[9px] text-gray-500 ml-2">cortex.io/ideas</span>
                </div>
                <div className="p-3 space-y-2">
                  {/* Professional chart area */}
                  <div className="h-36 bg-[#0a0e17] rounded-lg relative overflow-hidden">
                    <div className="absolute top-1.5 left-2 right-2 flex items-center justify-between z-10">
                      <span className="text-[8px] font-bold text-orange-400">AI Signals Performance</span>
                      <div className="flex items-center gap-1">
                        <span className="text-[7px] text-emerald-400 font-bold">+34%</span>
                        <span className="text-[7px] text-gray-500">today</span>
                      </div>
                    </div>
                    <svg className="w-full h-full" viewBox="0 0 300 100" preserveAspectRatio="none">
                      <defs>
                        <linearGradient id="ideaGrad" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="0%" stopColor="#f97316" stopOpacity="0.35"/>
                          <stop offset="100%" stopColor="#f97316" stopOpacity="0"/>
                        </linearGradient>
                      </defs>
                      {[25,50,75].map(y=><line key={y} x1="0" y1={y} x2="300" y2={y} stroke="#ffffff06" strokeWidth="1"/>)}
                      {[75,150,225].map(x=><line key={x} x1={x} y1="0" x2={x} y2="100" stroke="#ffffff06" strokeWidth="1"/>)}
                      <path d="M0,82 C15,80 25,86 40,74 C55,62 65,70 80,56 C95,42 105,50 120,38 C135,26 145,32 160,22 C175,12 185,16 200,11 C215,7 225,9 240,7 C255,5 270,8 300,4 L300,100 L0,100Z" fill="url(#ideaGrad)"/>
                      <path d="M0,82 C15,80 25,86 40,74 C55,62 65,70 80,56 C95,42 105,50 120,38 C135,26 145,32 160,22 C175,12 185,16 200,11 C215,7 225,9 240,7 C255,5 270,8 300,4" stroke="#f97316" strokeWidth="2.5" fill="none"/>
                      <path d="M0,90 C40,87 80,82 120,72 C160,62 200,50 240,38 C265,30 285,24 300,20" stroke="#6366f1" strokeWidth="1.2" fill="none" strokeDasharray="3,2" opacity="0.8"/>
                      {/* Candles */}
                      {[[20,80,75,83],[50,68,62,72],[80,54,49,58],[110,40,35,44],[140,28,23,32],[170,18,14,22],[200,12,8,15],[230,8,5,11],[265,5,3,7]].map(([x,o,h,l],i)=>(
                        <g key={i}>
                          <line x1={x} y1={l} x2={x} y2={h} stroke={i%3===2?'#ef4444':'#f97316'} strokeWidth="0.8" opacity="0.9"/>
                          <rect x={x-3} y={Math.min(o,h)} width="6" height={Math.max(Math.abs(h-o),2)} fill={i%3===2?'#ef4444':'#f97316'} opacity="0.8"/>
                        </g>
                      ))}
                    </svg>
                    <div className="absolute bottom-0 left-0 right-0 flex items-end gap-px h-4 px-0.5">
                      {[20,35,25,50,30,60,45,35,55,40,68,52,75].map((h,i)=>(
                        <div key={i} className="flex-1 rounded-t-sm" style={{height:`${h}%`,background:i%3===2?'rgba(239,68,68,0.35)':'rgba(249,115,22,0.35)'}}/>
                      ))}
                    </div>
                    <div className="absolute right-1 top-8 bottom-4 flex flex-col justify-between">
                      {['+67%','+34%','+12%','0%'].map((l,i)=><span key={i} className="text-[7px] text-gray-600">{l}</span>)}
                    </div>
                  </div>
                  {/* AI Ideas list */}
                  <div className="space-y-1">
                    {[
                      ['BTC Long 10x','Signal: Breakout','95% conf','+34%'],
                      ['ETH Short 5x','Signal: Reversal','88% conf','+21%'],
                      ['DOGE Long 25x','Signal: Momentum','91% conf','+67%'],
                      ['TSLA Long 2x','Signal: Earnings','82% conf','+18%'],
                    ].map(([a,s,c,r],i)=>(
                      <div key={i} className="flex items-center gap-2 bg-[#161b22] rounded px-2 py-1.5">
                        <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 flex-shrink-0"/>
                        <div className="flex-1 min-w-0">
                          <p className="text-[9px] font-semibold text-white">{a}</p>
                          <p className="text-[8px] text-gray-500">{s}</p>
                        </div>
                        <span className="text-[8px] text-blue-400">{c}</span>
                        <span className="text-[9px] font-bold text-emerald-400">{r}</span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
              {/* ORTEX icon watermark */}
              <div className="flex justify-center mt-3">
                <svg width="32" height="32" viewBox="0 0 32 32" fill="none">
                  <circle cx="16" cy="16" r="16" fill="hsl(174,65%,38%)" opacity="0.2"/>
                  <circle cx="10" cy="16" r="5" fill="hsl(174,65%,38%)" opacity="0.5"/>
                  <circle cx="22" cy="16" r="5" fill="hsl(174,65%,38%)" opacity="0.3"/>
                </svg>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Staking rewards block */}
        <div className="border-t border-gray-100 pt-16">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div initial={{opacity:0,x:-20}} whileInView={{opacity:1,x:0}} viewport={{once:true}}>
              <h2 className="font-display font-bold text-gray-900 mb-4" style={{fontSize:'2rem'}}>Daily Staking Rewards</h2>
              <p className="text-gray-600 font-display mb-6">
                Stake your assets and earn <strong>15% interest every 24 hours</strong> — compounding automatically. Top stakers compete for our weekly $10,000 USDT prize pool.
              </p>
              <div className="grid grid-cols-2 gap-4 mb-6">
                {[['15% / day','Daily Interest'],['$10,000 USDT','Weekly Pool'],['Top 3','Winners'],['Any time','Withdraw']].map(([v,l],i)=>(
                  <div key={i} className="p-4 rounded-xl border border-gray-200 bg-gray-50">
                    <p className="font-display text-2xl font-bold mb-1" style={{color:'hsl(174,65%,38%)'}}>{v}</p>
                    <p className="text-sm text-gray-500 font-display">{l}</p>
                  </div>
                ))}
              </div>
              <Link to="/register"><Button className="bg-red-500 hover:bg-red-600 text-white font-display font-semibold px-8 h-11 rounded-full">Start Staking</Button></Link>
            </motion.div>
            {/* Weekly leaderboard card */}
            <motion.div initial={{opacity:0,x:20}} whileInView={{opacity:1,x:0}} viewport={{once:true}}>
              <div className="rounded-2xl overflow-hidden border border-gray-200 shadow-lg">
                <div className="px-5 py-4 text-white font-display font-semibold flex items-center justify-between" style={{background:'linear-gradient(90deg,hsl(174,65%,30%),hsl(185,68%,42%))'}}>
                  <span>Weekly Leaderboard</span><span className="text-sm font-normal opacity-80">$10,000 USDT pool</span>
                </div>
                <div className="p-5 space-y-3 bg-white">
                  {[{r:'🥇',w:'0xA1B…C9D',s:'$284,200',rw:'$4,200'},{r:'🥈',w:'0x7E2…F11',s:'$198,400',rw:'$3,300'},{r:'🥉',w:'0xB9C…44A',s:'$142,800',rw:'$2,500'}].map((e,i)=>(
                    <div key={i} className="flex items-center gap-4 p-3 rounded-xl bg-gray-50 border border-gray-100">
                      <span className="text-xl">{e.r}</span>
                      <div className="flex-1"><p className="font-semibold text-sm">{e.w}</p><p className="text-xs text-gray-400">Staked: {e.s}</p></div>
                      <div className="text-right"><p className="font-bold text-emerald-600">{e.rw}</p><p className="text-xs text-gray-400">reward</p></div>
                    </div>
                  ))}
                  <p className="text-xs text-center text-gray-400 pt-2">Resets Monday 00:00 UTC · Next reset in 3d 14h</p>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </section>
  );
}